### ISSUE TITLE
Combining two models generated with SKLearn/SKLearn2PMML

### ISSUE THREAD

**Issue by sdroste** [vruusmann/jpmml-toolkit#1]
Dear Villu,

I have generated two different PMML regression models using Scikit Learn and sklearn2pmml and want to build a combined model (e.g. outputting the maximum of the values of the two different models).

I found and built this project, jpmml-toolkit, but when applying it for model aggregation (using the command you have given in the "Usage" section), I get the error message:

_Exception in thread "main" java.lang.IllegalArgumentException: http://www.dmg.org/PMML-4_3_

So is it right, that jpmml-toolkit cannot cope with PMML version 4.3? If so, are there any plans to update jpmml-toolkit? Or do you know of another general way to build a combined model (using max, min resp. OR, AND) from single PMML models?

Thank you very much
Stefan

**Comment by vruusmann** [comment]
> So is it right, that jpmml-toolkit cannot cope with PMML version 4.3?

JPMML-Toolkit was published/last updated in April 2016, when there was no PMML 4.3 available.

> If so, are there any plans to update jpmml-toolkit?

You could try updating the JPMML-Converter dependency version from `1.0.3` to `1.2.6`:
https://github.com/vruusmann/jpmml-toolkit/blob/master/pom.xml#L19

If the project builds without Java compilation errors, then the resulting Java application should fully support PMML schema version 4.3. If the JPMML-Converter library version `1.2.6` does not compile, then you might try some older version(s) - some 1.1.X version perhaps.

> Or do you know of another general way to build a combined model (using max, min resp. OR, AND) from single PMML models?

There are no plans to revive the JPMML-Toolkit project.

If your models are mainly coming from Scikit-Learn, then the solution will come this way:
https://github.com/jpmml/jpmml-sklearn/issues/52
